language: node_js
sudo: false
node_js:
  - '5.0'

cache:
  directories:
    - node_modules

before_install:

install:

before_script:
  - which chromium-browser
  - export CHROME_BIN=/usr/bin/chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma grunt-cli jshint
  - npm install # install npm packages

script:
  - grunt

after_success:

after_failure:

after_script:

branches:
  only:
    - master
    - develop

notifications:
  email: false
